### ISSUE TITLE
PSTV Cant Update Plugins on 3.69

### ISSUE THREAD

**Issue by itylermartin** [theheroGAC/Autoplugin#127]
PSTV Cant Update Plugins on 3.69 Version of Auto Plugin Over Wired Connection. Gives Error "Low Wifi Signal"

**Comment by itylermartin** [comment]
On a Wired Connection With Enso 3.65. 

I Noticed There Was a Fix For an Older Version But Not the Newer 3.69

**Comment by bamhm182** [comment]
I bought a PSTV last week. It is currently on 3.20, so I'm planning on doing a YouTube video on how to upgrade on with USB as soon as I can get my capture card working, then I plan on tackling this issue. It has been known about. Thanks for opening a ticket so we don't forget though! :)

**Comment by ONElua** [comment]
and the auto-update works well?

**Comment by bamhm182** [comment]
I don't know. I haven't given it a shot yet.

**Comment by itylermartin** [comment]
> and the auto-update works well?

The "Update Plugins" Feature Does Not Work In the "Auto Plugin App Version 3.69"

My PsTv is Connected Over Wired Connection. Gives Error "Low Wifi Signal" When Trying to Update Plugins.

Worked Just Fine on Previous Version of the App

**Comment by bamhm182** [comment]
I finally got around to installing 3.60 Enso on my PSTV and was able to test Autoplugin with Ethernet. I see the issue from this ticket and it seems like something we should be able to solve pretty easily.

@theheroGAC Is there a reason we check to see if wifi signal is low? It seems to me like we could just check to see if we can download a file (Maybe version because it is very small) for our "Are we online?" test.
